/**
 * @public
 */
export interface Option {
  'all-proxy'?: string
  'all-proxy-passwd'?: string
  'all-proxy-user'?: string
  'allow-overwrite'?: string
  'allow-piece-length-change'?: string
  'always-resume'?: string
  'async-dns'?: string
  'auto-file-renaming'?: string
  'bt-enable-hook-after-hash-check'?: string
  'bt-enable-lpd'?: string
  'bt-exclude-tracker'?: string
  'bt-external-ip'?: string
  'bt-force-encryption'?: string
  'bt-hash-check-seed'?: string
  'bt-load-saved-metadata'?: string
  'bt-max-peers'?: string
  'bt-metadata-only'?: string
  'bt-min-crypto-level'?: string
  'bt-prioritize-piece'?: string
  'bt-remove-unselected-file'?: string
  'bt-request-peer-speed-limit'?: string
  'bt-require-crypto'?: string
  'bt-save-metadata'?: string
  'bt-seed-unverified'?: string
  'bt-stop-timeout'?: string
  'bt-tracker'?: string
  'bt-tracker-connect-timeout'?: string
  'bt-tracker-interval'?: string
  'bt-tracker-timeout'?: string
  'check-integrity'?: string
  checksum?: string
  'conditional-get'?: string
  'connect-timeout'?: string
  'content-disposition-default-utf8'?: string
  continue?: string
  dir?: string
  'dry-run'?: string
  'enable-http-keep-alive'?: string
  'enable-http-pipelining'?: string
  'enable-mmap'?: string
  'enable-peer-exchange'?: string
  'file-allocation'?: string
  'follow-metalink'?: string
  'follow-torrent'?: string
  'force-save'?: string
  'ftp-passwd'?: string
  'ftp-pasv'?: string
  'ftp-proxy'?: string
  'ftp-proxy-passwd'?: string
  'ftp-proxy-user'?: string
  'ftp-reuse-connection'?: string
  'ftp-type'?: string
  'ftp-user'?: string
  gid?: string
  'hash-check-only'?: string
  header?: string
  'http-accept-gzip'?: string
  'http-auth-challenge'?: string
  'http-no-cache'?: string
  'http-passwd'?: string
  'http-proxy'?: string
  'http-proxy-passwd'?: string
  'http-proxy-user'?: string
  'http-user'?: string
  'https-proxy'?: string
  'https-proxy-passwd'?: string
  'https-proxy-user'?: string
  'index-out'?: string
  'lowest-speed-limit'?: string
  'max-connection-per-server'?: string
  'max-download-limit'?: string
  'max-file-not-found'?: string
  'max-mmap-limit'?: string
  'max-resume-failure-tries'?: string
  'max-tries'?: string
  'max-upload-limit'?: string
  'metalink-base-uri'?: string
  'metalink-enable-unique-protocol'?: string
  'metalink-language'?: string
  'metalink-location'?: string
  'metalink-os'?: string
  'metalink-preferred-protocol'?: string
  'metalink-version'?: string
  'min-split-size'?: string
  'no-file-allocation-limit'?: string
  'no-netrc'?: string
  'no-proxy'?: string
  out?: string
  'parameterized-uri'?: string
  pause?: string
  'pause-metadata'?: string
  'piece-length'?: string
  'proxy-method'?: string
  'realtime-chunk-checksum'?: string
  referer?: string
  'remote-time'?: string
  'remove-control-file'?: string
  'retry-wait'?: string
  'reuse-uri'?: string
  'rpc-save-upload-metadata'?: string
  'seed-ratio'?: string
  'seed-time'?: string
  'select-file'?: string
  split?: string
  'ssh-host-key-md'?: string
  'stream-piece-selector'?: string
  timeout?: string
  'uri-selector'?: string
  'use-head'?: string
  'user-agent'?: string
  [key: string]: string | undefined
}
